const productos = [
    {
        "id": 1,
        "slug": "laptop-lenovo-core-i5",
        "nombre": "Laptop Lenovo Core i5",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "laptops",
        "marca": "Lenovo",
        "precio": 1899,
        "precioAnterior": 2199,
        "stock": 15,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/laptop-lenovo.svg",
        "descripcion": "Laptop referencial para oficina, estudios, navegación, videollamadas y trabajo administrativo. Buena opción para usuarios que necesitan rapidez y almacenamiento SSD.",
        "caracteristicas": [
            "Procesador Intel Core i5 referencial",
            "Memoria RAM 12GB referencial",
            "SSD 512GB referencial",
            "Pantalla 15.6 pulgadas Full HD",
            "WiFi, Bluetooth, USB y HDMI",
            "Garantía referencial de 12 meses"
        ]
    },
    {
        "id": 2,
        "slug": "laptop-hp-ryzen-5",
        "nombre": "Laptop HP Ryzen 5",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "laptops",
        "marca": "HP",
        "precio": 2099,
        "precioAnterior": 2399,
        "stock": 8,
        "nuevo": true,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/laptop-hp.svg",
        "descripcion": "Laptop referencial para trabajo, clases, oficina y tareas multitarea. Modelo simulado con procesador Ryzen y almacenamiento sólido.",
        "caracteristicas": [
            "Procesador AMD Ryzen 5 referencial",
            "RAM 16GB referencial",
            "SSD 512GB referencial",
            "Pantalla Full HD",
            "Diseño portátil",
            "Consultar disponibilidad por WhatsApp"
        ]
    },
    {
        "id": 3,
        "slug": "monitor-samsung-24",
        "nombre": "Monitor Samsung 24 pulgadas",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "monitores",
        "marca": "Samsung",
        "precio": 549,
        "precioAnterior": 699,
        "stock": 12,
        "nuevo": false,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/monitor-samsung.svg",
        "descripcion": "Monitor ideal para oficina, estudio, cámaras, caja y uso diario. Buen tamaño para trabajar con varias ventanas.",
        "caracteristicas": [
            "Tamaño 24 pulgadas referencial",
            "Resolución Full HD",
            "Entrada HDMI/VGA referencial",
            "Base incluida",
            "Diseño delgado",
            "Garantía referencial"
        ]
    },
    {
        "id": 4,
        "slug": "kit-gamer-rgb",
        "nombre": "Kit Gamer RGB teclado y mouse",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "kits",
        "marca": "Genérico",
        "precio": 129,
        "precioAnterior": 0,
        "stock": 25,
        "nuevo": true,
        "oferta": false,
        "tag": "Más vendido",
        "imagen": "img/productos/kit-gamer.svg",
        "descripcion": "Combo gamer referencial para PC o laptop. Incluye teclado y mouse con iluminación RGB.",
        "caracteristicas": [
            "Teclado con iluminación RGB",
            "Mouse óptico",
            "Conexión USB",
            "Compatible con Windows",
            "Diseño gamer",
            "Producto de uso diario"
        ]
    },
    {
        "id": 5,
        "slug": "impresora-hp-laserjet",
        "nombre": "Impresora HP LaserJet",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "impresoras",
        "marca": "HP",
        "precio": 499,
        "precioAnterior": 0,
        "stock": 10,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/impresora-hp.svg",
        "descripcion": "Impresora láser referencial para oficina, boletas, documentos, guías y uso administrativo.",
        "caracteristicas": [
            "Tecnología láser",
            "Impresión monocromática",
            "Formato A4",
            "Conexión USB o WiFi según modelo",
            "Bajo costo por página referencial",
            "Consultar tóner compatible"
        ]
    },
    {
        "id": 6,
        "slug": "cargador-laptop-universal",
        "nombre": "Cargador Laptop Universal",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "cargadores",
        "marca": "Universal",
        "precio": 85,
        "precioAnterior": 0,
        "stock": 20,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/cargador-laptop.svg",
        "descripcion": "Cargador referencial compatible con varios modelos de laptop. Consultar voltaje y punta antes de comprar.",
        "caracteristicas": [
            "Voltaje referencial según modelo",
            "Puntas intercambiables",
            "Protección básica",
            "Uso para laptop",
            "Consultar compatibilidad",
            "Stock sujeto a disponibilidad"
        ]
    },
    {
        "id": 7,
        "slug": "fuente-poder-600w",
        "nombre": "Fuente de Poder 600W",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "componentes",
        "marca": "Genérico",
        "precio": 180,
        "precioAnterior": 0,
        "stock": 7,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/fuente-poder.svg",
        "descripcion": "Fuente de poder referencial para PC de escritorio. Ideal para armado, mantenimiento o reemplazo.",
        "caracteristicas": [
            "Potencia referencial 600W",
            "Conectores principales para PC",
            "Uso en gabinete estándar",
            "Consultar certificación disponible",
            "Instalación recomendada por técnico"
        ]
    },
    {
        "id": 8,
        "slug": "router-wifi-doble-banda",
        "nombre": "Router WiFi Doble Banda",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "redes",
        "marca": "TP-Link",
        "precio": 139,
        "precioAnterior": 0,
        "stock": 9,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/router-wifi.svg",
        "descripcion": "Router referencial para mejorar cobertura WiFi en casa, oficina o pequeño negocio.",
        "caracteristicas": [
            "Doble banda referencial",
            "Puertos LAN",
            "Configuración básica",
            "Ideal para hogar y oficina",
            "Consultar cobertura según ambiente"
        ]
    },
    {
        "id": 20,
        "slug": "tubos-pvc",
        "nombre": "Tubos PVC",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "tubos",
        "marca": "PVC",
        "precio": 25,
        "precioAnterior": 0,
        "stock": 30,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/tubos-pvc.svg",
        "descripcion": "Tubos PVC referenciales para instalaciones sanitarias, eléctricas o de construcción ligera.",
        "caracteristicas": [
            "Material PVC",
            "Diferentes diámetros referenciales",
            "Uso sanitario o eléctrico según modelo",
            "Venta por unidad",
            "Consultar medida disponible"
        ]
    },
    {
        "id": 21,
        "slug": "taladro-electrico",
        "nombre": "Taladro eléctrico",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "herramientas",
        "marca": "Genérico",
        "precio": 189,
        "precioAnterior": 229,
        "stock": 6,
        "nuevo": false,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/taladro.svg",
        "descripcion": "Taladro eléctrico referencial para trabajos de hogar, instalación, mantenimiento y construcción ligera.",
        "caracteristicas": [
            "Uso doméstico y semi profesional",
            "Velocidad variable referencial",
            "Mandril estándar",
            "Compatible con brocas comunes",
            "Consultar potencia según stock"
        ]
    },
    {
        "id": 22,
        "slug": "cables-de-luz",
        "nombre": "Cables de luz",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "electricidad",
        "marca": "Genérico",
        "precio": 35,
        "precioAnterior": 0,
        "stock": 40,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/cables-luz.svg",
        "descripcion": "Cables eléctricos referenciales para instalaciones domiciliarias y comerciales ligeras.",
        "caracteristicas": [
            "Venta por rollo o metro según stock",
            "Diferentes calibres",
            "Uso eléctrico",
            "Consultar certificación y tipo",
            "Stock sujeto a disponibilidad"
        ]
    },
    {
        "id": 23,
        "slug": "pintura-latex",
        "nombre": "Pintura látex",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "pinturas",
        "marca": "Genérico",
        "precio": 65,
        "precioAnterior": 0,
        "stock": 18,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/pintura.svg",
        "descripcion": "Pintura látex referencial para interiores o exteriores según modelo disponible.",
        "caracteristicas": [
            "Presentación referencial por galón",
            "Colores variados",
            "Uso interior o exterior según tipo",
            "Consultar rendimiento",
            "Aplicación con brocha o rodillo"
        ]
    },
    {
        "id": 40,
        "slug": "decoracion-para-sala",
        "nombre": "Decoración para sala",
        "linea": "Hogar",
        "categoria": "hogar",
        "subcategoria": "decoracion",
        "marca": "Mica Home",
        "precio": 79,
        "precioAnterior": 0,
        "stock": 14,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/decoracion-sala.svg",
        "descripcion": "Artículo decorativo para sala o dormitorio. Ideal para dar estilo moderno, cálido y ordenado al ambiente.",
        "caracteristicas": [
            "Diseño decorativo",
            "Uso en sala o dormitorio",
            "Material referencial según modelo",
            "Fácil ubicación",
            "Consultar colores disponibles"
        ]
    },
    {
        "id": 41,
        "slug": "cojines-decorativos",
        "nombre": "Cojines decorativos",
        "linea": "Hogar",
        "categoria": "hogar",
        "subcategoria": "textiles",
        "marca": "Mica Home",
        "precio": 45,
        "precioAnterior": 59,
        "stock": 22,
        "nuevo": false,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/cojines.svg",
        "descripcion": "Cojines referenciales para sala, dormitorio o decoración de espacios modernos.",
        "caracteristicas": [
            "Textura suave referencial",
            "Diseños variados",
            "Uso decorativo",
            "Consultar colores disponibles",
            "Venta por unidad o set según stock"
        ]
    },
    {
        "id": 42,
        "slug": "organizadores-para-casa",
        "nombre": "Organizadores para casa",
        "linea": "Hogar",
        "categoria": "hogar",
        "subcategoria": "organizacion",
        "marca": "Mica Home",
        "precio": 39,
        "precioAnterior": 0,
        "stock": 16,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/organizadores.svg",
        "descripcion": "Organizadores para mantener orden en cocina, dormitorio, baño o sala.",
        "caracteristicas": [
            "Diseños variados",
            "Uso multiambiente",
            "Fácil limpieza",
            "Material según modelo",
            "Consultar medidas"
        ]
    },
    {
        "id": 60,
        "slug": "set-skincare-facial",
        "nombre": "Set Skincare facial",
        "linea": "Belleza y Cuidado Personal",
        "categoria": "belleza",
        "subcategoria": "skincare",
        "marca": "Mica Beauty",
        "precio": 50,
        "precioAnterior": 0,
        "stock": 20,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/skincare.svg",
        "descripcion": "Set referencial de cuidado facial para rutina diaria. Ideal para limpieza, hidratación y cuidado básico de la piel.",
        "caracteristicas": [
            "Productos de cuidado facial",
            "Uso diario referencial",
            "Consultar tipo de piel",
            "Consultar marcas disponibles",
            "Stock sujeto a disponibilidad"
        ]
    },
    {
        "id": 61,
        "slug": "labiales-mate",
        "nombre": "Labiales mate",
        "linea": "Belleza y Cuidado Personal",
        "categoria": "belleza",
        "subcategoria": "labiales",
        "marca": "Mica Beauty",
        "precio": 25,
        "precioAnterior": 35,
        "stock": 30,
        "nuevo": false,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/labiales.svg",
        "descripcion": "Labiales de acabado mate en tonos variados para uso diario, eventos o maquillaje casual.",
        "caracteristicas": [
            "Acabado mate referencial",
            "Tonos variados",
            "Consultar stock por color",
            "Uso personal",
            "Producto sujeto a disponibilidad"
        ]
    },
    {
        "id": 62,
        "slug": "serum-facial",
        "nombre": "Serum facial",
        "linea": "Belleza y Cuidado Personal",
        "categoria": "belleza",
        "subcategoria": "skincare",
        "marca": "Mica Beauty",
        "precio": 65,
        "precioAnterior": 80,
        "stock": 12,
        "nuevo": true,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/serum.svg",
        "descripcion": "Serum facial referencial para complementar la rutina de skincare.",
        "caracteristicas": [
            "Uso facial",
            "Aplicación diaria referencial",
            "Consultar tipo de piel",
            "Producto sujeto a disponibilidad",
            "No reemplaza recomendación dermatológica"
        ]
    },
    {
        "id": 63,
        "slug": "microsoft-365-personal-1-ano",
        "nombre": "Microsoft 365 Personal 1 año",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Microsoft",
        "precio": 249,
        "precioAnterior": 0,
        "stock": 7,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/microsoft-365-personal-1-ano.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Microsoft 365 Personal 1 año con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 64,
        "slug": "microsoft-365-family-1-ano",
        "nombre": "Microsoft 365 Family 1 año",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Microsoft",
        "precio": 329,
        "precioAnterior": 0,
        "stock": 3,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/microsoft-365-family-1-ano.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Microsoft 365 Family 1 año con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 65,
        "slug": "microsoft-365-business-basic",
        "nombre": "Microsoft 365 Business Basic",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Microsoft",
        "precio": 29,
        "precioAnterior": 0,
        "stock": 8,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/microsoft-365-business-basic.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Microsoft 365 Business Basic con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 66,
        "slug": "microsoft-365-business-standard",
        "nombre": "Microsoft 365 Business Standard",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Microsoft",
        "precio": 65,
        "precioAnterior": 0,
        "stock": 4,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/microsoft-365-business-standard.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Microsoft 365 Business Standard con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 67,
        "slug": "microsoft-365-business-premium",
        "nombre": "Microsoft 365 Business Premium",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Microsoft",
        "precio": 99,
        "precioAnterior": 0,
        "stock": 17,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/microsoft-365-business-premium.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Microsoft 365 Business Premium con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 68,
        "slug": "windows-11-pro-licencia-digital",
        "nombre": "Windows 11 Pro licencia digital",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Microsoft",
        "precio": 399,
        "precioAnterior": 0,
        "stock": 9,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/windows-11-pro-licencia-digital.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Windows 11 Pro licencia digital con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 69,
        "slug": "windows-server-standard-licencia",
        "nombre": "Windows Server Standard licencia",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Microsoft",
        "precio": 3200,
        "precioAnterior": 0,
        "stock": 8,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/windows-server-standard-licencia.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Windows Server Standard licencia con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 70,
        "slug": "sql-server-standard-licencia",
        "nombre": "SQL Server Standard licencia",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Microsoft",
        "precio": 4500,
        "precioAnterior": 0,
        "stock": 10,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/sql-server-standard-licencia.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. SQL Server Standard licencia con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 71,
        "slug": "adobe-photoshop-licencia-anual",
        "nombre": "Adobe Photoshop licencia anual",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Adobe",
        "precio": 899,
        "precioAnterior": 999,
        "stock": 12,
        "nuevo": true,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/adobe-photoshop-licencia-anual.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Adobe Photoshop licencia anual con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 72,
        "slug": "adobe-illustrator-licencia-anual",
        "nombre": "Adobe Illustrator licencia anual",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Adobe",
        "precio": 899,
        "precioAnterior": 999,
        "stock": 12,
        "nuevo": true,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/adobe-illustrator-licencia-anual.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Adobe Illustrator licencia anual con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 73,
        "slug": "adobe-creative-cloud-anual",
        "nombre": "Adobe Creative Cloud anual",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Adobe",
        "precio": 2699,
        "precioAnterior": 2999,
        "stock": 19,
        "nuevo": true,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/adobe-creative-cloud-anual.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Adobe Creative Cloud anual con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 74,
        "slug": "adobe-acrobat-pro-anual",
        "nombre": "Adobe Acrobat Pro anual",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Adobe",
        "precio": 780,
        "precioAnterior": 0,
        "stock": 20,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/adobe-acrobat-pro-anual.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Adobe Acrobat Pro anual con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 75,
        "slug": "autocad-licencia-anual",
        "nombre": "AutoCAD licencia anual",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Autodesk",
        "precio": 5200,
        "precioAnterior": 0,
        "stock": 17,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/autocad-licencia-anual.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. AutoCAD licencia anual con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 76,
        "slug": "coreldraw-graphics-suite",
        "nombre": "CorelDRAW Graphics Suite",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Corel",
        "precio": 1800,
        "precioAnterior": 0,
        "stock": 7,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/coreldraw-graphics-suite.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. CorelDRAW Graphics Suite con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 77,
        "slug": "eset-small-business-security",
        "nombre": "ESET Small Business Security",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "ESET",
        "precio": 420,
        "precioAnterior": 0,
        "stock": 7,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/eset-small-business-security.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. ESET Small Business Security con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 78,
        "slug": "bitdefender-gravityzone",
        "nombre": "Bitdefender GravityZone",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Bitdefender",
        "precio": 380,
        "precioAnterior": 0,
        "stock": 8,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/bitdefender-gravityzone.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Bitdefender GravityZone con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 79,
        "slug": "acronis-cyber-protect",
        "nombre": "Acronis Cyber Protect",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Acronis",
        "precio": 480,
        "precioAnterior": 0,
        "stock": 8,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/acronis-cyber-protect.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Acronis Cyber Protect con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 80,
        "slug": "veeam-backup-essentials",
        "nombre": "Veeam Backup Essentials",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "licencias",
        "marca": "Veeam",
        "precio": 1500,
        "precioAnterior": 0,
        "stock": 7,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/veeam-backup-essentials.svg",
        "descripcion": "Licencia ficticia/referencial para demostración del catálogo. Veeam Backup Essentials con entrega digital y activación asistida previa validación de disponibilidad.",
        "caracteristicas": [
            "Entrega digital referencial",
            "Activación asistida",
            "Producto sujeto a disponibilidad",
            "Consultar modalidad de licencia",
            "No incluye implementación avanzada salvo indicación"
        ]
    },
    {
        "id": 81,
        "slug": "mantenimiento-de-pc-de-escritorio",
        "nombre": "Mantenimiento de PC de escritorio",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "servicios-ti",
        "marca": "Mica Servicios",
        "precio": 90,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/mantenimiento-de-pc-de-escritorio.svg",
        "descripcion": "Servicio técnico referencial: Mantenimiento de PC de escritorio. Se cotiza según diagnóstico, ubicación y complejidad del trabajo.",
        "caracteristicas": [
            "Atención previa coordinación",
            "Diagnóstico referencial",
            "Precio base sujeto a evaluación",
            "Servicio en local o domicilio según zona"
        ]
    },
    {
        "id": 82,
        "slug": "migracion-de-correos-microsoft-365",
        "nombre": "Migración de correos Microsoft 365",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "servicios-ti",
        "marca": "Mica Servicios",
        "precio": 350,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/migracion-de-correos-microsoft-365.svg",
        "descripcion": "Servicio técnico referencial: Migración de correos Microsoft 365. Se cotiza según diagnóstico, ubicación y complejidad del trabajo.",
        "caracteristicas": [
            "Atención previa coordinación",
            "Diagnóstico referencial",
            "Precio base sujeto a evaluación",
            "Servicio en local o domicilio según zona"
        ]
    },
    {
        "id": 83,
        "slug": "implementacion-microsoft-365-basica",
        "nombre": "Implementación Microsoft 365 básica",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "servicios-ti",
        "marca": "Mica Servicios",
        "precio": 450,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/implementacion-microsoft-365-basica.svg",
        "descripcion": "Servicio técnico referencial: Implementación Microsoft 365 básica. Se cotiza según diagnóstico, ubicación y complejidad del trabajo.",
        "caracteristicas": [
            "Atención previa coordinación",
            "Diagnóstico referencial",
            "Precio base sujeto a evaluación",
            "Servicio en local o domicilio según zona"
        ]
    },
    {
        "id": 84,
        "slug": "instalacion-de-camaras-de-seguridad",
        "nombre": "Instalación de cámaras de seguridad",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "servicios-ti",
        "marca": "Mica Servicios",
        "precio": 250,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/instalacion-de-camaras-de-seguridad.svg",
        "descripcion": "Servicio técnico referencial: Instalación de cámaras de seguridad. Se cotiza según diagnóstico, ubicación y complejidad del trabajo.",
        "caracteristicas": [
            "Atención previa coordinación",
            "Diagnóstico referencial",
            "Precio base sujeto a evaluación",
            "Servicio en local o domicilio según zona"
        ]
    },
    {
        "id": 85,
        "slug": "configuracion-de-red-wifi",
        "nombre": "Configuración de red WiFi",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "servicios-ti",
        "marca": "Mica Servicios",
        "precio": 120,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/configuracion-de-red-wifi.svg",
        "descripcion": "Servicio técnico referencial: Configuración de red WiFi. Se cotiza según diagnóstico, ubicación y complejidad del trabajo.",
        "caracteristicas": [
            "Atención previa coordinación",
            "Diagnóstico referencial",
            "Precio base sujeto a evaluación",
            "Servicio en local o domicilio según zona"
        ]
    },
    {
        "id": 86,
        "slug": "instalacion-de-servidor-basico",
        "nombre": "Instalación de servidor básico",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "servicios-ti",
        "marca": "Mica Servicios",
        "precio": 650,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/instalacion-de-servidor-basico.svg",
        "descripcion": "Servicio técnico referencial: Instalación de servidor básico. Se cotiza según diagnóstico, ubicación y complejidad del trabajo.",
        "caracteristicas": [
            "Atención previa coordinación",
            "Diagnóstico referencial",
            "Precio base sujeto a evaluación",
            "Servicio en local o domicilio según zona"
        ]
    },
    {
        "id": 87,
        "slug": "consultoria-ti-por-hora",
        "nombre": "Consultoría TI por hora",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "servicios-ti",
        "marca": "Mica Servicios",
        "precio": 120,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/consultoria-ti-por-hora.svg",
        "descripcion": "Servicio técnico referencial: Consultoría TI por hora. Se cotiza según diagnóstico, ubicación y complejidad del trabajo.",
        "caracteristicas": [
            "Atención previa coordinación",
            "Diagnóstico referencial",
            "Precio base sujeto a evaluación",
            "Servicio en local o domicilio según zona"
        ]
    },
    {
        "id": 88,
        "slug": "servicio-de-electricidad-domiciliaria",
        "nombre": "Servicio de electricidad domiciliaria",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 180,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/servicio-de-electricidad-domiciliaria.svg",
        "descripcion": "Servicio referencial de servicio de electricidad domiciliaria. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 89,
        "slug": "servicio-de-electricidad-industrial",
        "nombre": "Servicio de electricidad industrial",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 350,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/servicio-de-electricidad-industrial.svg",
        "descripcion": "Servicio referencial de servicio de electricidad industrial. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 90,
        "slug": "servicio-de-gasfiteria",
        "nombre": "Servicio de gasfitería",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 150,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/servicio-de-gasfiteria.svg",
        "descripcion": "Servicio referencial de servicio de gasfitería. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 91,
        "slug": "instalacion-de-bombas-de-agua",
        "nombre": "Instalación de bombas de agua",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 250,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/instalacion-de-bombas-de-agua.svg",
        "descripcion": "Servicio referencial de instalación de bombas de agua. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 92,
        "slug": "instalacion-de-termas",
        "nombre": "Instalación de termas",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 180,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/instalacion-de-termas.svg",
        "descripcion": "Servicio referencial de instalación de termas. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 93,
        "slug": "remodelacion-de-ambientes",
        "nombre": "Remodelación de ambientes",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 650,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/remodelacion-de-ambientes.svg",
        "descripcion": "Servicio referencial de remodelación de ambientes. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 94,
        "slug": "enchapado-de-pisos",
        "nombre": "Enchapado de pisos",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 45,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/enchapado-de-pisos.svg",
        "descripcion": "Servicio referencial de enchapado de pisos. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 95,
        "slug": "enchapado-de-paredes",
        "nombre": "Enchapado de paredes",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 50,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/enchapado-de-paredes.svg",
        "descripcion": "Servicio referencial de enchapado de paredes. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 96,
        "slug": "tarrajeo-de-paredes",
        "nombre": "Tarrajeo de paredes",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 38,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/tarrajeo-de-paredes.svg",
        "descripcion": "Servicio referencial de tarrajeo de paredes. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 97,
        "slug": "pintura-interior-y-exterior",
        "nombre": "Pintura interior y exterior",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 35,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/pintura-interior-y-exterior.svg",
        "descripcion": "Servicio referencial de pintura interior y exterior. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 98,
        "slug": "drywall-y-cielo-raso",
        "nombre": "Drywall y cielo raso",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 75,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/drywall-y-cielo-raso.svg",
        "descripcion": "Servicio referencial de drywall y cielo raso. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 99,
        "slug": "instalacion-de-porcelanato",
        "nombre": "Instalación de porcelanato",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 55,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/instalacion-de-porcelanato.svg",
        "descripcion": "Servicio referencial de instalación de porcelanato. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 100,
        "slug": "instalacion-de-ceramica",
        "nombre": "Instalación de cerámica",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 45,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/instalacion-de-ceramica.svg",
        "descripcion": "Servicio referencial de instalación de cerámica. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 101,
        "slug": "soldadura-y-estructuras-metalicas",
        "nombre": "Soldadura y estructuras metálicas",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 280,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/soldadura-y-estructuras-metalicas.svg",
        "descripcion": "Servicio referencial de soldadura y estructuras metálicas. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 102,
        "slug": "instalacion-de-puertas-y-ventanas",
        "nombre": "Instalación de puertas y ventanas",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 220,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/instalacion-de-puertas-y-ventanas.svg",
        "descripcion": "Servicio referencial de instalación de puertas y ventanas. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 103,
        "slug": "carpinteria-y-melamina",
        "nombre": "Carpintería y melamina",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 300,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/carpinteria-y-melamina.svg",
        "descripcion": "Servicio referencial de carpintería y melamina. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 104,
        "slug": "obras-civiles-en-general",
        "nombre": "Obras civiles en general",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 1200,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/obras-civiles-en-general.svg",
        "descripcion": "Servicio referencial de obras civiles en general. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 105,
        "slug": "mantenimiento-preventivo-de-local",
        "nombre": "Mantenimiento preventivo de local",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 400,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/mantenimiento-preventivo-de-local.svg",
        "descripcion": "Servicio referencial de mantenimiento preventivo de local. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 106,
        "slug": "mantenimiento-correctivo-de-vivienda",
        "nombre": "Mantenimiento correctivo de vivienda",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 350,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/mantenimiento-correctivo-de-vivienda.svg",
        "descripcion": "Servicio referencial de mantenimiento correctivo de vivienda. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 107,
        "slug": "diseno-de-interiores-basico",
        "nombre": "Diseño de interiores básico",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "servicios-construccion",
        "marca": "Mica Obras",
        "precio": 500,
        "precioAnterior": 0,
        "stock": 99,
        "nuevo": true,
        "oferta": false,
        "tag": "Servicio",
        "imagen": "img/productos/diseno-de-interiores-basico.svg",
        "descripcion": "Servicio referencial de diseño de interiores básico. El precio final depende de visita técnica, medidas, materiales, zona y complejidad.",
        "caracteristicas": [
            "Cotización previa por WhatsApp",
            "Puede requerir visita técnica",
            "Precio base referencial",
            "Materiales no incluidos salvo indicación",
            "Atención en Lima y provincias según coordinación"
        ]
    },
    {
        "id": 108,
        "slug": "llave-de-lavatorio",
        "nombre": "Llave de lavatorio",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "gasfiteria",
        "marca": "Vainsa",
        "precio": 55,
        "precioAnterior": 0,
        "stock": 24,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/llave-de-lavatorio.svg",
        "descripcion": "Llave de lavatorio referencial de la línea Ferretería y Construcción. Producto o servicio de demostración para Mica Store. Consultar disponibilidad, precio final y condiciones por WhatsApp.",
        "caracteristicas": [
            "Categoría: gasfiteria",
            "Marca o línea referencial: Vainsa",
            "Precio y stock referenciales",
            "Atención por WhatsApp 24 horas"
        ]
    },
    {
        "id": 109,
        "slug": "pegamento-pvc",
        "nombre": "Pegamento PVC",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "gasfiteria",
        "marca": "Genérico",
        "precio": 18,
        "precioAnterior": 0,
        "stock": 31,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/pegamento-pvc.svg",
        "descripcion": "Pegamento PVC referencial de la línea Ferretería y Construcción. Producto o servicio de demostración para Mica Store. Consultar disponibilidad, precio final y condiciones por WhatsApp.",
        "caracteristicas": [
            "Categoría: gasfiteria",
            "Marca o línea referencial: Genérico",
            "Precio y stock referenciales",
            "Atención por WhatsApp 24 horas"
        ]
    },
    {
        "id": 110,
        "slug": "cerradura-de-puerta",
        "nombre": "Cerradura de puerta",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "cerraduras",
        "marca": "Genérico",
        "precio": 75,
        "precioAnterior": 0,
        "stock": 40,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/cerradura-de-puerta.svg",
        "descripcion": "Cerradura de puerta referencial de la línea Ferretería y Construcción. Producto o servicio de demostración para Mica Store. Consultar disponibilidad, precio final y condiciones por WhatsApp.",
        "caracteristicas": [
            "Categoría: cerraduras",
            "Marca o línea referencial: Genérico",
            "Precio y stock referenciales",
            "Atención por WhatsApp 24 horas"
        ]
    },
    {
        "id": 111,
        "slug": "guantes-de-seguridad",
        "nombre": "Guantes de seguridad",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "seguridad-industrial",
        "marca": "3M",
        "precio": 25,
        "precioAnterior": 0,
        "stock": 6,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/guantes-de-seguridad.svg",
        "descripcion": "Guantes de seguridad referencial de la línea Ferretería y Construcción. Producto o servicio de demostración para Mica Store. Consultar disponibilidad, precio final y condiciones por WhatsApp.",
        "caracteristicas": [
            "Categoría: seguridad-industrial",
            "Marca o línea referencial: 3M",
            "Precio y stock referenciales",
            "Atención por WhatsApp 24 horas"
        ]
    },
    {
        "id": 112,
        "slug": "casco-de-seguridad",
        "nombre": "Casco de seguridad",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "seguridad-industrial",
        "marca": "Genérico",
        "precio": 35,
        "precioAnterior": 0,
        "stock": 11,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/casco-de-seguridad.svg",
        "descripcion": "Casco de seguridad referencial de la línea Ferretería y Construcción. Producto o servicio de demostración para Mica Store. Consultar disponibilidad, precio final y condiciones por WhatsApp.",
        "caracteristicas": [
            "Categoría: seguridad-industrial",
            "Marca o línea referencial: Genérico",
            "Precio y stock referenciales",
            "Atención por WhatsApp 24 horas"
        ]
    },
    {
        "id": 113,
        "slug": "botas-de-seguridad",
        "nombre": "Botas de seguridad",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "seguridad-industrial",
        "marca": "Genérico",
        "precio": 120,
        "precioAnterior": 0,
        "stock": 32,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/botas-de-seguridad.svg",
        "descripcion": "Botas de seguridad referencial de la línea Ferretería y Construcción. Producto o servicio de demostración para Mica Store. Consultar disponibilidad, precio final y condiciones por WhatsApp.",
        "caracteristicas": [
            "Categoría: seguridad-industrial",
            "Marca o línea referencial: Genérico",
            "Precio y stock referenciales",
            "Atención por WhatsApp 24 horas"
        ]
    },
    {
        "id": 114,
        "slug": "brocha-profesional",
        "nombre": "Brocha profesional",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "pinturas",
        "marca": "Genérico",
        "precio": 12,
        "precioAnterior": 0,
        "stock": 20,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/brocha-profesional.svg",
        "descripcion": "Brocha profesional referencial de la línea Ferretería y Construcción. Producto o servicio de demostración para Mica Store. Consultar disponibilidad, precio final y condiciones por WhatsApp.",
        "caracteristicas": [
            "Categoría: pinturas",
            "Marca o línea referencial: Genérico",
            "Precio y stock referenciales",
            "Atención por WhatsApp 24 horas"
        ]
    },
    {
        "id": 115,
        "slug": "rodillo-para-pintura",
        "nombre": "Rodillo para pintura",
        "linea": "Ferretería y Construcción",
        "categoria": "ferreteria",
        "subcategoria": "pinturas",
        "marca": "Genérico",
        "precio": 18,
        "precioAnterior": 0,
        "stock": 13,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/rodillo-para-pintura.svg",
        "descripcion": "Rodillo para pintura referencial de la línea Ferretería y Construcción. Producto o servicio de demostración para Mica Store. Consultar disponibilidad, precio final y condiciones por WhatsApp.",
        "caracteristicas": [
            "Categoría: pinturas",
            "Marca o línea referencial: Genérico",
            "Precio y stock referenciales",
            "Atención por WhatsApp 24 horas"
        ]
    },
    {
        "id": 116,
        "slug": "toner-hp-105a-compatible",
        "nombre": "Tóner HP 105A compatible",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "toners",
        "marca": "Compatible",
        "precio": 85,
        "precioAnterior": 0,
        "stock": 15,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/toner-hp-105a-compatible.svg",
        "descripcion": "Tóner HP 105A compatible referencial para impresoras. Consultar compatibilidad con el modelo antes de comprar.",
        "caracteristicas": [
            "Tóner compatible referencial",
            "Consultar modelo exacto de impresora",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 117,
        "slug": "toner-hp-85a-compatible",
        "nombre": "Tóner HP 85A compatible",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "toners",
        "marca": "Compatible",
        "precio": 75,
        "precioAnterior": 0,
        "stock": 15,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/toner-hp-85a-compatible.svg",
        "descripcion": "Tóner HP 85A compatible referencial para impresoras. Consultar compatibilidad con el modelo antes de comprar.",
        "caracteristicas": [
            "Tóner compatible referencial",
            "Consultar modelo exacto de impresora",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 118,
        "slug": "toner-brother-tn-1060-compatible",
        "nombre": "Tóner Brother TN-1060 compatible",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "toners",
        "marca": "Compatible",
        "precio": 70,
        "precioAnterior": 0,
        "stock": 15,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/toner-brother-tn-1060-compatible.svg",
        "descripcion": "Tóner Brother TN-1060 compatible referencial para impresoras. Consultar compatibilidad con el modelo antes de comprar.",
        "caracteristicas": [
            "Tóner compatible referencial",
            "Consultar modelo exacto de impresora",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 119,
        "slug": "toner-canon-057-compatible",
        "nombre": "Tóner Canon 057 compatible",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "toners",
        "marca": "Compatible",
        "precio": 110,
        "precioAnterior": 135,
        "stock": 15,
        "nuevo": true,
        "oferta": true,
        "tag": "Oferta",
        "imagen": "img/productos/toner-canon-057-compatible.svg",
        "descripcion": "Tóner Canon 057 compatible referencial para impresoras. Consultar compatibilidad con el modelo antes de comprar.",
        "caracteristicas": [
            "Tóner compatible referencial",
            "Consultar modelo exacto de impresora",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 120,
        "slug": "toner-samsung-mlt-d111s-compatible",
        "nombre": "Tóner Samsung MLT-D111S compatible",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "toners",
        "marca": "Compatible",
        "precio": 80,
        "precioAnterior": 0,
        "stock": 15,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/toner-samsung-mlt-d111s-compatible.svg",
        "descripcion": "Tóner Samsung MLT-D111S compatible referencial para impresoras. Consultar compatibilidad con el modelo antes de comprar.",
        "caracteristicas": [
            "Tóner compatible referencial",
            "Consultar modelo exacto de impresora",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 121,
        "slug": "toner-xerox-compatible",
        "nombre": "Tóner Xerox compatible",
        "linea": "Tecnología",
        "categoria": "tecnologia",
        "subcategoria": "toners",
        "marca": "Compatible",
        "precio": 95,
        "precioAnterior": 0,
        "stock": 15,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/toner-xerox-compatible.svg",
        "descripcion": "Tóner Xerox compatible referencial para impresoras. Consultar compatibilidad con el modelo antes de comprar.",
        "caracteristicas": [
            "Tóner compatible referencial",
            "Consultar modelo exacto de impresora",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 122,
        "slug": "set-vajilla-familiar",
        "nombre": "Set vajilla familiar",
        "linea": "Hogar",
        "categoria": "hogar",
        "subcategoria": "cocina",
        "marca": "Mica Store",
        "precio": 110,
        "precioAnterior": 0,
        "stock": 10,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/set-vajilla-familiar.svg",
        "descripcion": "Set vajilla familiar referencial para la línea Hogar.",
        "caracteristicas": [
            "Producto referencial",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 123,
        "slug": "lampara-decorativa",
        "nombre": "Lámpara decorativa",
        "linea": "Hogar",
        "categoria": "hogar",
        "subcategoria": "iluminacion",
        "marca": "Mica Store",
        "precio": 99,
        "precioAnterior": 0,
        "stock": 10,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/lampara-decorativa.svg",
        "descripcion": "Lámpara decorativa referencial para la línea Hogar.",
        "caracteristicas": [
            "Producto referencial",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 124,
        "slug": "organizador-multiuso",
        "nombre": "Organizador multiuso",
        "linea": "Hogar",
        "categoria": "hogar",
        "subcategoria": "organizacion",
        "marca": "Mica Store",
        "precio": 49,
        "precioAnterior": 0,
        "stock": 10,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/organizador-multiuso.svg",
        "descripcion": "Organizador multiuso referencial para la línea Hogar.",
        "caracteristicas": [
            "Producto referencial",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 125,
        "slug": "perfume-floral",
        "nombre": "Perfume floral",
        "linea": "Belleza y Cuidado Personal",
        "categoria": "belleza",
        "subcategoria": "perfumes",
        "marca": "Mica Store",
        "precio": 75,
        "precioAnterior": 0,
        "stock": 10,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/perfume-floral.svg",
        "descripcion": "Perfume floral referencial para la línea Belleza y Cuidado Personal.",
        "caracteristicas": [
            "Producto referencial",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 126,
        "slug": "base-liquida-natural",
        "nombre": "Base líquida natural",
        "linea": "Belleza y Cuidado Personal",
        "categoria": "belleza",
        "subcategoria": "maquillaje",
        "marca": "Mica Store",
        "precio": 48,
        "precioAnterior": 0,
        "stock": 10,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/base-liquida-natural.svg",
        "descripcion": "Base líquida natural referencial para la línea Belleza y Cuidado Personal.",
        "caracteristicas": [
            "Producto referencial",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    },
    {
        "id": 127,
        "slug": "bloqueador-solar-facial",
        "nombre": "Bloqueador solar facial",
        "linea": "Belleza y Cuidado Personal",
        "categoria": "belleza",
        "subcategoria": "skincare",
        "marca": "Mica Store",
        "precio": 45,
        "precioAnterior": 0,
        "stock": 10,
        "nuevo": true,
        "oferta": false,
        "tag": "Nuevo",
        "imagen": "img/productos/bloqueador-solar-facial.svg",
        "descripcion": "Bloqueador solar facial referencial para la línea Belleza y Cuidado Personal.",
        "caracteristicas": [
            "Producto referencial",
            "Precio y stock referenciales",
            "Atención por WhatsApp"
        ]
    }
];