CREATE TABLE IF NOT EXISTS contacto_mensajes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(160) NOT NULL,
  correo VARCHAR(160) NULL,
  celular VARCHAR(40) NULL,
  asunto VARCHAR(180) NULL,
  mensaje TEXT NOT NULL,
  acepta_contacto TINYINT DEFAULT 0,
  estado VARCHAR(40) DEFAULT 'Nuevo',
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
