<?php
require_once "../config/db.php";
require_once "layout.php";
$producto_id = $_GET['producto_id'] ?? 0;
$stmt = $pdo->prepare("SELECT * FROM productos WHERE id = ?"); $stmt->execute([$producto_id]); $producto = $stmt->fetch(PDO::FETCH_ASSOC);
if(!$producto){ die("Producto no encontrado"); } if(!erp_producto_en_scope($pdo,(int)$producto_id)){ http_response_code(403); die('Acceso restringido. Este producto no pertenece a tus categorías permitidas.'); }
$stmt = $pdo->prepare("SELECT * FROM inventario_movimientos WHERE producto_id = ? ORDER BY id DESC"); $stmt->execute([$producto_id]); $movimientos = $stmt->fetchAll(PDO::FETCH_ASSOC);
$stockActual=(int)($producto['stock']??0); $stockMinimo=(int)($producto['stock_minimo']??0);
if($stockActual<=0){$estadoClase='zero';$estadoTexto='🔴 Sin stock';}elseif($stockActual<=$stockMinimo){$estadoClase='low';$estadoTexto='🟡 Stock bajo';}else{$estadoClase='ok';$estadoTexto='🟢 Stock normal';}
admin_header("Historial de inventario", "inventario");
?>
<style>.tipo-entrada{color:#16a34a;font-weight:bold}.tipo-salida{color:#dc2626;font-weight:bold}.tipo-ajuste{color:#2563eb;font-weight:bold}.summary{background:#f8fafc;border:1px solid #e5e7eb;border-radius:18px;padding:18px;margin-bottom:18px}.stock-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:16px 0}.stock-card{background:white;border:1px solid #e5e7eb;border-radius:16px;padding:16px}.stock-card small{display:block;color:#64748b;font-weight:800}.stock-card strong{font-size:24px}.estado{display:inline-block;border-radius:999px;padding:8px 12px;font-weight:900}.estado.ok{background:#dcfce7;color:#166534}.estado.low{background:#fef3c7;color:#92400e}.estado.zero{background:#fee2e2;color:#991b1b}@media(max-width:800px){.stock-cards{grid-template-columns:1fr}}</style>
<div class="panel"><div class="panel-header"><h3>Historial de inventario</h3><a class="btn gray" href="inventario.php">Volver</a></div><div class="summary"><h3><?= htmlspecialchars($producto['nombre']) ?></h3><div class="stock-cards"><div class="stock-card"><small>Stock actual</small><strong><?= $stockActual ?></strong></div><div class="stock-card"><small>Stock mínimo</small><strong><?= $stockMinimo ?></strong></div><div class="stock-card"><small>Estado</small><span class="estado <?= $estadoClase ?>"><?= $estadoTexto ?></span></div></div><a class="btn green" href="inventario_movimiento.php?producto_id=<?= (int)$producto['id'] ?>&tipo=Entrada">Nueva entrada</a> <a class="btn red" href="inventario_movimiento.php?producto_id=<?= (int)$producto['id'] ?>&tipo=Salida">Nueva salida</a> <a class="btn gray" href="inventario_movimiento.php?producto_id=<?= (int)$producto['id'] ?>&tipo=Ajuste">Nuevo ajuste</a></div>
<table class="table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Cantidad</th><th>Stock anterior</th><th>Stock nuevo</th><th>Motivo</th><th>Referencia</th><th>Usuario</th></tr></thead><tbody>
<?php foreach($movimientos as $m): ?><?php $clase='tipo-ajuste';$signo=''; if($m['tipo']==='Entrada'){$clase='tipo-entrada';$signo='+';} if($m['tipo']==='Salida'){$clase='tipo-salida';$signo='-';} ?><tr><td><?= htmlspecialchars($m['creado_en']) ?></td><td class="<?= $clase ?>"><?= htmlspecialchars($m['tipo']) ?></td><td><?= $signo ?><?= abs((int)$m['cantidad']) ?></td><td><?= (int)$m['stock_anterior'] ?></td><td><?= (int)$m['stock_nuevo'] ?></td><td><?= htmlspecialchars($m['motivo']) ?></td><td><?= htmlspecialchars($m['referencia']) ?></td><td><?= htmlspecialchars($m['usuario']) ?></td></tr><?php endforeach; ?>
<?php if(count($movimientos)===0): ?><tr><td colspan="8">Este producto todavía no tiene movimientos de inventario.</td></tr><?php endif; ?></tbody></table></div><?php admin_footer(); ?>