<?php
require_once "../config/db.php";
require_once "layout.php";
$producto_id = $_GET['producto_id'] ?? 0; $tipo = $_GET['tipo'] ?? 'Entrada'; if(!in_array($tipo,['Entrada','Salida','Ajuste'])) $tipo='Entrada';
$stmt=$pdo->prepare("SELECT * FROM productos WHERE id = ?"); $stmt->execute([$producto_id]); $producto=$stmt->fetch(PDO::FETCH_ASSOC);
if(!$producto){ die("Producto no encontrado"); } if(!erp_producto_en_scope($pdo,(int)$producto_id)){ http_response_code(403); die('Acceso restringido. Este producto no pertenece a tus categorías permitidas.'); } if(($producto['tipo_item'] ?? 'producto') === 'servicio'){ die("Este ítem es un servicio y no maneja inventario."); }
$mensaje='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $tipo=$_POST['tipo'] ?? 'Entrada'; if(!in_array($tipo,['Entrada','Salida','Ajuste'])) $tipo='Entrada';
    $cantidad=(int)($_POST['cantidad'] ?? 0); $motivoSelect=trim($_POST['motivo_select'] ?? ''); $motivoOtro=trim($_POST['motivo_otro'] ?? ''); $referencia=trim($_POST['referencia'] ?? '');
    $motivo=$motivoSelect==='Otro' ? $motivoOtro : $motivoSelect; $stockAnterior=(int)$producto['stock'];
    if($cantidad<=0){$mensaje='La cantidad debe ser mayor a 0.';} elseif($motivo===''){$mensaje='Selecciona o escribe un motivo.';} else {
        if($tipo==='Entrada'){$stockNuevo=$stockAnterior+$cantidad;} elseif($tipo==='Salida'){$stockNuevo=$stockAnterior-$cantidad; if($stockNuevo<0)$mensaje='No puedes sacar más unidades que el stock disponible.';} else {$stockNuevo=$cantidad;}
        if($mensaje===''){
            $pdo->beginTransaction(); $stmt=$pdo->prepare("UPDATE productos SET stock=? WHERE id=?"); $stmt->execute([$stockNuevo,$producto_id]); $cantidadMovimiento=$tipo==='Ajuste'?($stockNuevo-$stockAnterior):$cantidad; $usuario=$_SESSION['admin_nombre'] ?? $_SESSION['admin_usuario'] ?? 'Admin';
            $stmt=$pdo->prepare("INSERT INTO inventario_movimientos (producto_id,tipo,cantidad,stock_anterior,stock_nuevo,motivo,referencia,usuario) VALUES (?,?,?,?,?,?,?,?)"); $stmt->execute([$producto_id,$tipo,$cantidadMovimiento,$stockAnterior,$stockNuevo,$motivo,$referencia,$usuario]); $pdo->commit(); header("Location: inventario_historial.php?producto_id=".$producto_id); exit;
        }
    }
}
$stockActual=(int)($producto['stock']??0); $stockMinimo=(int)($producto['stock_minimo']??0); if($stockActual<=0){$estadoClase='zero';$estadoTexto='🔴 Sin stock';}elseif($stockActual<=$stockMinimo){$estadoClase='low';$estadoTexto='🟡 Stock bajo';}else{$estadoClase='ok';$estadoTexto='🟢 Stock normal';}
$stmt=$pdo->prepare("SELECT * FROM inventario_movimientos WHERE producto_id=? ORDER BY id DESC LIMIT 8"); $stmt->execute([$producto_id]); $ultimosMovimientos=$stmt->fetchAll(PDO::FETCH_ASSOC);
admin_header("Movimiento de inventario", "inventario");
?>
<style>.notice-error{background:#fee2e2;color:#991b1b;border:1px solid #fecaca;padding:12px;border-radius:10px;margin-bottom:15px;font-weight:bold}.product-summary{background:#f8fafc;border:1px solid #e5e7eb;border-radius:18px;padding:18px;margin-bottom:18px}.stock-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:14px}.stock-card{background:white;border:1px solid #e5e7eb;border-radius:16px;padding:16px}.stock-card small{display:block;color:#64748b;font-weight:800}.stock-card strong{font-size:24px}.estado{display:inline-block;border-radius:999px;padding:8px 12px;font-weight:900}.estado.ok{background:#dcfce7;color:#166534}.estado.low{background:#fef3c7;color:#92400e}.estado.zero{background:#fee2e2;color:#991b1b}.movimiento-help{background:#eef2ff;color:#1e3a8a;border-radius:12px;padding:12px;margin-top:12px;font-weight:800}.otro-box{display:none}.validacion-stock{display:none;margin-top:8px;border-radius:10px;padding:10px;font-weight:900}.validacion-stock.error{display:block;background:#fee2e2;color:#991b1b}.validacion-stock.ok{display:block;background:#dcfce7;color:#166534}.tipo-entrada{color:#16a34a;font-weight:bold}.tipo-salida{color:#dc2626;font-weight:bold}.tipo-ajuste{color:#2563eb;font-weight:bold}@media(max-width:800px){.stock-cards{grid-template-columns:1fr}}</style>
<div class="panel"><div class="panel-header"><h3><?= htmlspecialchars($tipo) ?> de inventario</h3><a class="btn gray" href="inventario.php">Volver</a></div><?php if($mensaje): ?><div class="notice-error"><?= htmlspecialchars($mensaje) ?></div><?php endif; ?><div class="product-summary"><h3><?= htmlspecialchars($producto['nombre']) ?></h3><div class="stock-cards"><div class="stock-card"><small>Stock actual</small><strong id="stockActual"><?= $stockActual ?></strong></div><div class="stock-card"><small>Stock mínimo</small><strong><?= $stockMinimo ?></strong></div><div class="stock-card"><small>Estado</small><span class="estado <?= $estadoClase ?>"><?= $estadoTexto ?></span></div></div></div>
<form method="POST" id="formMovimiento"><div class="form-grid"><div class="form-group"><label>Tipo de movimiento</label><select name="tipo" id="tipoMovimiento"><option value="Entrada" <?= $tipo==='Entrada'?'selected':'' ?>>🟢 Entrada</option><option value="Salida" <?= $tipo==='Salida'?'selected':'' ?>>🔴 Salida</option><option value="Ajuste" <?= $tipo==='Ajuste'?'selected':'' ?>>🔵 Ajuste</option></select><div class="movimiento-help" id="tipoHelp"></div></div><div class="form-group"><label id="cantidadLabel">Cantidad</label><input type="number" name="cantidad" id="cantidad" min="1" required><div id="validacionStock" class="validacion-stock"></div></div><div class="form-group full"><label>Motivo</label><select name="motivo_select" id="motivoSelect"></select></div><div class="form-group full otro-box" id="otroBox"><label>Motivo personalizado</label><input name="motivo_otro" id="motivoOtro" placeholder="Escribe el motivo"></div><div class="form-group full"><label id="referenciaLabel">Referencia</label><input name="referencia" id="referencia" placeholder="Ejemplo: Factura F001-123, Cotización #15, Ajuste manual"></div></div><button class="btn green" type="submit">Guardar movimiento</button></form></div>
<div class="panel" style="margin-top:18px;"><div class="panel-header"><h3>Últimos movimientos</h3><a class="btn" href="inventario_historial.php?producto_id=<?= (int)$producto_id ?>">Ver historial completo</a></div><table class="table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Cantidad</th><th>Stock anterior</th><th>Stock nuevo</th><th>Motivo</th><th>Referencia</th></tr></thead><tbody><?php foreach($ultimosMovimientos as $m): ?><?php $clase='tipo-ajuste';$signo=''; if($m['tipo']==='Entrada'){$clase='tipo-entrada';$signo='+';} if($m['tipo']==='Salida'){$clase='tipo-salida';$signo='-';} ?><tr><td><?= htmlspecialchars($m['creado_en']) ?></td><td class="<?= $clase ?>"><?= htmlspecialchars($m['tipo']) ?></td><td><?= $signo ?><?= abs((int)$m['cantidad']) ?></td><td><?= (int)$m['stock_anterior'] ?></td><td><?= (int)$m['stock_nuevo'] ?></td><td><?= htmlspecialchars($m['motivo']) ?></td><td><?= htmlspecialchars($m['referencia']) ?></td></tr><?php endforeach; ?><?php if(count($ultimosMovimientos)===0): ?><tr><td colspan="7">Todavía no hay movimientos registrados.</td></tr><?php endif; ?></tbody></table></div>
<script>
const motivos={Entrada:["Compra a proveedor","Devolución de cliente","Ajuste por conteo","Producción","Transferencia recibida","Donación recibida","Otro"],Salida:["Venta","Merma","Producto dañado","Producto vencido","Consumo interno","Regalo / Promoción","Devolución a proveedor","Transferencia entre almacenes","Ajuste por conteo","Robo / Pérdida","Otro"],Ajuste:["Conteo físico","Corrección de stock","Error de registro","Ajuste inicial","Otro"]};
const tipo=document.getElementById('tipoMovimiento'), motivoSelect=document.getElementById('motivoSelect'), otroBox=document.getElementById('otroBox'), motivoOtro=document.getElementById('motivoOtro'), labelCantidad=document.getElementById('cantidadLabel'), referenciaLabel=document.getElementById('referenciaLabel'), referencia=document.getElementById('referencia'), cantidad=document.getElementById('cantidad'), validacion=document.getElementById('validacionStock'), stockActual=Number(document.getElementById('stockActual').textContent||0), tipoHelp=document.getElementById('tipoHelp');
function cargarMotivos(){const t=tipo.value; motivoSelect.innerHTML=''; motivos[t].forEach(m=>{const opt=document.createElement('option'); opt.value=m; opt.textContent=m; motivoSelect.appendChild(opt);}); if(t==='Ajuste'){labelCantidad.textContent='Stock final real'; tipoHelp.textContent='En ajuste, la cantidad representa el stock final real después del conteo.';}else{labelCantidad.textContent='Cantidad'; tipoHelp.textContent=t==='Entrada'?'La cantidad se sumará al stock actual.':'La cantidad se restará del stock actual.';} actualizarReferencia(); validarStock();}
function actualizarReferencia(){const m=motivoSelect.value; otroBox.style.display=m==='Otro'?'block':'none'; if(m!=='Otro') motivoOtro.value=''; if(m==='Compra a proveedor'){referenciaLabel.textContent='Factura / proveedor'; referencia.placeholder='Ejemplo: Proveedor ABC SAC - F001-000123';}else if(m==='Venta'){referenciaLabel.textContent='Cotización / venta'; referencia.placeholder='Ejemplo: Cotización #15 o Boleta F001-000123';}else if(m.includes('Transferencia')){referenciaLabel.textContent='Almacén / destino'; referencia.placeholder='Ejemplo: Almacén Central a Tienda';}else if(['Merma','Producto dañado','Producto vencido'].includes(m)){referenciaLabel.textContent='Detalle'; referencia.placeholder='Ejemplo: Producto roto, vencido o deteriorado';}else{referenciaLabel.textContent='Referencia'; referencia.placeholder='Ejemplo: Ajuste manual, conteo físico, observación';}}
function validarStock(){const t=tipo.value,cant=Number(cantidad.value||0); validacion.className='validacion-stock'; validacion.style.display='none'; validacion.textContent=''; if(cant<=0)return; if(t==='Salida'){if(cant>stockActual){validacion.classList.add('error'); validacion.textContent='❌ No hay suficiente stock. Disponible: '+stockActual+' unidades.';}else{validacion.classList.add('ok'); validacion.textContent='✅ Stock suficiente. Quedarán '+(stockActual-cant)+' unidades.';}} if(t==='Entrada'){validacion.classList.add('ok'); validacion.textContent='✅ Nuevo stock: '+(stockActual+cant)+' unidades.';} if(t==='Ajuste'){validacion.classList.add('ok'); validacion.textContent='✅ El stock final quedará en '+cant+' unidades.';}}
document.getElementById('formMovimiento').addEventListener('submit',function(e){if(tipo.value==='Salida'&&Number(cantidad.value||0)>stockActual){e.preventDefault(); validarStock(); alert('No puedes sacar más unidades que el stock disponible.');} if(motivoSelect.value==='Otro'&&motivoOtro.value.trim()===''){e.preventDefault(); alert('Escribe el motivo personalizado.'); motivoOtro.focus();}});
tipo.addEventListener('change',cargarMotivos); motivoSelect.addEventListener('change',actualizarReferencia); cantidad.addEventListener('input',validarStock); cargarMotivos();
</script><?php admin_footer(); ?>