<?php
require_once "../config/db.php";
require_once "layout.php";
function h($v){ return htmlspecialchars((string)$v, ENT_QUOTES, "UTF-8"); }
$id=(int)($_GET['id']??0);
$puesto=['titulo'=>'','area'=>'','modalidad'=>'Presencial','ubicacion'=>'','vacantes'=>1,'salario'=>'','descripcion'=>'','requisitos'=>'','beneficios'=>'','fecha_limite'=>'','estado'=>'Activo','orden'=>0];
if($id>0){ $st=$pdo->prepare("SELECT * FROM rrhh_puestos WHERE id=?"); $st->execute([$id]); $row=$st->fetch(PDO::FETCH_ASSOC); if(!$row) die('Puesto no encontrado'); $puesto=array_merge($puesto,$row); }
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        $titulo=trim($_POST['titulo']??''); if($titulo==='') throw new Exception('El título es obligatorio.');
        $datos=[$titulo,trim($_POST['area']??''),trim($_POST['modalidad']??''),trim($_POST['ubicacion']??''),(int)($_POST['vacantes']??1),trim($_POST['salario']??''),trim($_POST['descripcion']??''),trim($_POST['requisitos']??''),trim($_POST['beneficios']??''),($_POST['fecha_limite']??'')?:null,$_POST['estado']??'Activo',(int)($_POST['orden']??0)];
        if($id>0){ $pdo->prepare("UPDATE rrhh_puestos SET titulo=?,area=?,modalidad=?,ubicacion=?,vacantes=?,salario=?,descripcion=?,requisitos=?,beneficios=?,fecha_limite=?,estado=?,orden=? WHERE id=?")->execute([...$datos,$id]); erp_auditoria($pdo,'rrhh','editar','Editó puesto','rrhh_puestos',$id); }
        else{ $pdo->prepare("INSERT INTO rrhh_puestos (titulo,area,modalidad,ubicacion,vacantes,salario,descripcion,requisitos,beneficios,fecha_limite,estado,orden) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)")->execute($datos); $id=(int)$pdo->lastInsertId(); erp_auditoria($pdo,'rrhh','crear','Creó puesto','rrhh_puestos',$id); }
        header('Location: rrhh_puestos.php?ok=1'); exit;
    }catch(Exception $e){ $error=$e->getMessage(); }
}
admin_header($id?'Editar puesto':'Nuevo puesto','rrhh');
?>
<style>.job-layout{display:grid;grid-template-columns:1.3fr .7fr;gap:22px}.help{color:#64748b;font-size:13px;margin-top:6px}@media(max-width:900px){.job-layout{grid-template-columns:1fr}}</style>
<div class="job-layout"><div class="panel"><div class="panel-header"><h3><?= $id?'Editar puesto':'Nuevo puesto' ?></h3><a class="btn gray" href="rrhh_puestos.php">Volver</a></div><?php if($error): ?><div style="background:#fee2e2;color:#991b1b;padding:12px;border-radius:12px;margin-bottom:14px;font-weight:900"><?= h($error) ?></div><?php endif; ?><form method="POST"><div class="form-grid"><div class="form-group full"><label>Puesto</label><input name="titulo" required value="<?= h($puesto['titulo']) ?>" placeholder="Ejemplo: Asistente de ventas"></div><div class="form-group"><label>Área</label><input name="area" value="<?= h($puesto['area']) ?>" placeholder="Ventas, TI, Almacén"></div><div class="form-group"><label>Modalidad</label><select name="modalidad"><option <?= $puesto['modalidad']==='Presencial'?'selected':'' ?>>Presencial</option><option <?= $puesto['modalidad']==='Remoto'?'selected':'' ?>>Remoto</option><option <?= $puesto['modalidad']==='Híbrido'?'selected':'' ?>>Híbrido</option></select></div><div class="form-group"><label>Ubicación</label><input name="ubicacion" value="<?= h($puesto['ubicacion']) ?>"></div><div class="form-group"><label>Vacantes</label><input type="number" min="1" name="vacantes" value="<?= h($puesto['vacantes']) ?>"></div><div class="form-group"><label>Salario</label><input name="salario" value="<?= h($puesto['salario']) ?>" placeholder="Opcional"></div><div class="form-group"><label>Fecha límite</label><input type="date" name="fecha_limite" value="<?= h($puesto['fecha_limite']) ?>"></div><div class="form-group"><label>Estado</label><select name="estado"><option <?= $puesto['estado']==='Activo'?'selected':'' ?>>Activo</option><option <?= $puesto['estado']==='Inactivo'?'selected':'' ?>>Inactivo</option><option <?= $puesto['estado']==='Cerrado'?'selected':'' ?>>Cerrado</option></select></div><div class="form-group"><label>Orden</label><input type="number" name="orden" value="<?= h($puesto['orden']) ?>"></div><div class="form-group full"><label>Descripción</label><textarea name="descripcion" rows="5"><?= h($puesto['descripcion']) ?></textarea></div><div class="form-group full"><label>Requisitos</label><textarea name="requisitos" rows="5"><?= h($puesto['requisitos']) ?></textarea></div><div class="form-group full"><label>Beneficios</label><textarea name="beneficios" rows="4"><?= h($puesto['beneficios']) ?></textarea></div><div class="form-group full"><button class="btn green">Guardar puesto</button></div></div></form></div><div class="panel"><h3>Consejo</h3><p class="help">Este puesto aparecerá automáticamente en la página pública “Trabaja con nosotros” cuando esté activo.</p><a class="btn" target="_blank" href="../trabaja_con_nosotros.php">Ver página pública</a></div></div>
<?php admin_footer(); ?>
