<?php
require_once "../config/db.php";
require_once "layout.php";
requerirPermiso('usuarios','ver');
function h($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
$buscar = trim($_GET['buscar'] ?? '');
$sql = "SELECT u.*, r.nombre AS rol_nombre, COUNT(uc.categoria_id) AS total_categorias FROM admin_usuarios u LEFT JOIN admin_roles r ON r.id=u.rol_id LEFT JOIN admin_usuario_categorias uc ON uc.usuario_id=u.id WHERE 1=1";
$params = [];
if($buscar !== ''){ $sql .= " AND (u.nombre LIKE :buscar OR u.usuario LIKE :buscar OR u.correo LIKE :buscar OR u.rol LIKE :buscar OR r.nombre LIKE :buscar)"; $params[':buscar'] = "%$buscar%"; }
$sql .= " GROUP BY u.id ORDER BY u.activo DESC, COALESCE(r.nombre,u.rol) ASC, u.nombre ASC";
$stmt = $pdo->prepare($sql); $stmt->execute($params); $usuarios = $stmt->fetchAll(PDO::FETCH_ASSOC);
$total = $pdo->query("SELECT COUNT(*) FROM admin_usuarios")->fetchColumn();
$activos = $pdo->query("SELECT COUNT(*) FROM admin_usuarios WHERE activo=1")->fetchColumn();
$bloqueados = $pdo->query("SELECT COUNT(*) FROM admin_usuarios WHERE bloqueado_hasta IS NOT NULL AND bloqueado_hasta > NOW()")->fetchColumn();
$roles = $pdo->query("SELECT COUNT(*) FROM admin_roles WHERE activo=1")->fetchColumn();
admin_header('Usuarios','usuarios');
?>
<style>.filter-box{display:grid;grid-template-columns:1fr 140px;gap:12px;margin-bottom:20px}.filter-box input{padding:12px;border:1px solid #e5e7eb;border-radius:10px;font-size:15px}.role-badge{display:inline-block;border-radius:999px;padding:7px 11px;font-size:12px;font-weight:900;background:#eef2ff;color:#1e40af}.role-badge.admin{background:#dcfce7;color:#166534}.muted{color:#64748b;font-size:13px}.lock{background:#fee2e2;color:#991b1b;border-radius:999px;padding:6px 10px;font-weight:900;font-size:12px}@media(max-width:800px){.filter-box{grid-template-columns:1fr}}</style>
<div class="cards"><div class="card"><small>Usuarios creados</small><strong><?= (int)$total ?></strong></div><div class="card"><small>Usuarios activos</small><strong><?= (int)$activos ?></strong></div><div class="card"><small>Bloqueados</small><strong><?= (int)$bloqueados ?></strong></div><div class="card"><small>Roles activos</small><strong><?= (int)$roles ?></strong></div></div>
<div class="panel"><div class="panel-header"><div><h3>Gestión de usuarios</h3><p class="muted">Crea usuarios internos, asigna rol, restablece contraseña y controla bloqueos.</p></div><?php if(rolPuede('usuarios','crear')): ?><a class="btn green" href="usuario_form.php">+ Nuevo usuario</a><?php endif; ?></div><?php if(isset($_GET['ok'])): ?><div style="background:#dcfce7;color:#166534;padding:14px;border-radius:12px;margin-bottom:18px;font-weight:bold;">Cambios guardados correctamente.</div><?php endif; ?><form class="filter-box" method="GET"><input name="buscar" value="<?= h($buscar) ?>" placeholder="Buscar por nombre, usuario, correo o rol"><button class="btn" type="submit">Buscar</button></form><table class="table"><thead><tr><th>ID</th><th>Usuario</th><th>Correo</th><th>Rol</th><th>Alcance</th><th>Último acceso</th><th>Seguridad</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php foreach($usuarios as $u): $bloq=!empty($u['bloqueado_hasta']) && strtotime($u['bloqueado_hasta'])>time(); ?><tr><td><?= (int)$u['id'] ?></td><td><strong><?= h($u['nombre']) ?></strong><br><small class="muted">@<?= h($u['usuario']) ?></small></td><td><?= h($u['correo'] ?: '-') ?></td><td><span class="role-badge <?= (($u['rol_nombre'] ?: $u['rol'])==='Administrador')?'admin':'' ?>"><?= h($u['rol_nombre'] ?: $u['rol'] ?: '-') ?></span></td><td><?php if(($u['rol_nombre'] ?: $u['rol'])==='Administrador'): ?><span class="role-badge admin">Todas</span><?php else: ?><small class="muted"><?= h(implode(', ', erp_categorias_permitidas_nombres($pdo,(int)$u['id'])) ?: 'Sin categorías' ) ?></small><?php endif; ?></td><td><?= h($u['ultimo_login'] ?: 'Nunca') ?><br><small class="muted"><?= h($u['ultimo_ip'] ?: '') ?></small></td><td><?php if($bloq): ?><span class="lock">Bloqueado</span><br><small><?= h($u['bloqueado_hasta']) ?></small><?php else: ?><small class="muted">Intentos: <?= (int)($u['intentos'] ?? 0) ?></small><?php endif; ?></td><td><span class="badge <?= !empty($u['activo']) ? 'ok' : 'warn' ?>"><?= !empty($u['activo']) ? 'Activo' : 'Inactivo' ?></span></td><td class="actions"><?php if(rolPuede('usuarios','editar')): ?><a class="btn gray" href="usuario_form.php?id=<?= (int)$u['id'] ?>">Editar</a><?php endif; ?><?php if((int)$u['id'] !== adminId() && rolPuede('usuarios','editar')): ?><a class="btn <?= !empty($u['activo'])?'red':'green' ?>" href="usuario_toggle.php?id=<?= (int)$u['id'] ?>" onclick="return confirm('¿Cambiar estado del usuario?')"><?= !empty($u['activo'])?'Desactivar':'Activar' ?></a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php admin_footer(); ?>
